// file: my_application_ui.slint
import { CheckBox, ListView, LineEdit } from "std-widgets.slint";
import { Button } from "thirdparty/surrealism/src/button/button.slint";

export struct Cell {
    number: int,
    posX: int,
    posY: int
}

export component MainWindow {
    in-out property<[Cell]> map;
    in-out property<int> menu: 0; // select menu - 0, game - 1
    in-out property<int> size: 0;
    in-out property<int> current: -1;
    in-out property<bool> win: false;
    width: 500px;
    height: 500px;

    callback initGame(int);
    callback showIndx1(int);
    callback onClickBtn(int);

    Rectangle {
        width: 100%;
        height: 100%;
        color: #00000000;

        if (menu == 0): Rectangle {
            width: 100%;
            height: 100%;
            color: #00000000;
            Button {
                color: #F5B042;
                width: 80px;
                height: 80px;
                x: 100px;
                y: 200px;
                text: "3x3";
                clicked => { initGame(3); }
            }
            Button {
                color: #F5B042;
                width: 80px;
                height: 80px;
                x: 300px;
                y: 200px;
                text: "4x4";
                clicked => { initGame(4); }
            }
        }
        
        if (menu == 1): Rectangle { // game
            x: 0px;
            y: 0px;
            width: 100%;
            height: 100%;
            color: #00000000;

            Button {
                x: 330px;
                y: 445px;
                width: 150px;
                height: 35px;
                text: "Back";
                clicked => { menu = 0; }
            }

            for cl[i] in map : Rectangle {
                if (i != current): Button {
                    color: #F5B042;
                    x: 90px + cl.posX * 80px;
                    y: 90px + cl.posY * 80px;
                    width: 80px;
                    height: 80px;
                    text: cl.number;
                    clicked => { onClickBtn(i); }
                }
            }
	    if(win == true) : Rectangle{
		x: 0px;
		y: 0px;
		width: 100%;
		height: 100%;
		color: #00EB3B66;
		Text {
		    font-size: 24pt;
		    text: "You win!";
		}
            }
        }
    }
}